log syslog all;
log stderr all;

include "/usr/local/etc/bird/active_tun_v4.inc";
include "/usr/local/etc/bird/active_tun_v6.inc";
include "/usr/local/etc/bird/communities.inc";
include "/usr/local/etc/bird/filters.inc";
include "/usr/local/etc/bird/router_id.inc";


# router id is set in router_id.inc from WAN IPv4 at install

protocol device {
    scan time 300;
}

protocol direct {
    ipv4;
    ipv6;
    interface "wan", "proxytun2socks0", "proxytun2socks1", "proxytun2socks2", "proxytun2socks3";
}

protocol kernel krt4 {
    scan time 60;
    learn;
    persist;
    ipv4 {
        import none;
        export all;
    };
}

protocol kernel krt6 {
    scan time 60;
    learn;
    persist;
    ipv6 {
        import none;
        export all;
    };
}

include "/usr/local/etc/bird/bgp.conf";
