log syslog all;
log stderr all;

include "/usr/local/etc/bird/active_tun_v4.inc";
include "/usr/local/etc/bird/active_tun_v6.inc";
include "/usr/local/etc/bird/community_antifilter_download.inc";
include "/usr/local/etc/bird/community_antifilter_network.inc";


filter accept_antifilter_download {
    if bgp_community ~ ANTIFILTER_DOWNLOAD then { 
       if net = 0.0.0.0/0 then reject;
       ifname = ACTIVE_TUN4_IF;
       accept;
    }
    reject; 
}

filter accept_antifilter_network_v4 { 
    if bgp_community ~ ANTIFILTER_NETWORK then {
       if net = 0.0.0.0/0 then reject;
       ifname = ACTIVE_TUN4_IF;
       accept;
    }
    reject;
}

filter accept_antifilter_network_v6 {
    if bgp_community ~ ANTIFILTER_NETWORK then {
       if net = ::/0 then reject;
       ifname = ACTIVE_TUN6_IF;
       accept;
    }
    reject;
}

filter accept_refilter {
    if net = 0.0.0.0/0 then reject;
    ifname = ACTIVE_TUN4_IF;
    accept;
}


# router id <WAN_IPv4>;

protocol device {
    scan time 300;
}

protocol direct {
    ipv4;
    ipv6;
    interface "wan", "proxytun2socks0", "proxytun2socks1", "proxytun2socks2", "proxytun2socks3";
}

protocol kernel krt4 {
    scan time 60;
    learn;
    persist;
    ipv4 {
        import none;
        export all;
    };
}

protocol kernel krt6 {
    scan time 60;
    learn;
    persist;
    ipv6 {
        import none;
        export all;
    };
}

include "/usr/local/etc/bird/bgp.conf";
