log syslog all;
log stderr all;

include "/usr/local/etc/bird/active_tun_v4.inc";
include "/usr/local/etc/bird/active_tun_v6.inc";

define ANTIFILTER_DOWNLOAD = [ (65432, 500) ];
define ANTIFILTER_NETWORK = [ (65444, 120), (65444, 200), (65444, 210), (65444, 700), (65444, 710), (65444, 720), (65444, 730), (65444, 740), (65444, 750), (65444, 760), (65444, 770), (65444, 780), (65444, 790), (65444, 800) ];


filter accept_antifilter_download {
    if bgp_community ~ ANTIFILTER_DOWNLOAD then { 
       if net = 0.0.0.0/0 then reject;
       ifname = ACTIVE_TUN4_IF;
       accept;
    }
    reject; 
}

filter accept_antifilter_network_v4 { 
    if bgp_community ~ ANTIFILTER_NETWORK then {
       if net = 0.0.0.0/0 then reject;
       ifname = ACTIVE_TUN4_IF;
       accept;
    }
    reject;
}

filter accept_antifilter_network_v6 {
    if bgp_community ~ ANTIFILTER_NETWORK then {
       if net = ::/0 then reject;
       ifname = ACTIVE_TUN6_IF;
       accept;
    }
    reject;
}

filter accept_refilter {
    if net = 0.0.0.0/0 then reject;
    ifname = ACTIVE_TUN4_IF;
    accept;
}


# router id <WAN_IPv4>;

protocol device {
    scan time 300;
}

protocol direct {
    ipv4;
    ipv6;
    interface "wan", "proxytun2socks0", "proxytun2socks1", "proxytun2socks2", "proxytun2socks3";
}

protocol kernel krt4 {
    scan time 60;
    learn;
    persist;
    ipv4 {
        import none;
        export all;
    };
}

protocol kernel krt6 {
    scan time 60;
    learn;
    persist;
    ipv6 {
        import none;
        export all;
    };
}


protocol bgp refilter {
    local as 65103;
    neighbor 165.22.127.207 as 65412;
    # source address <WAN_IPv4>;
    ipv4 {
        import filter accept_refilter;
        export none;
    };
    multihop;
    hold time 240;
}
protocol bgp antifilter_download {
    local as 65103;
    neighbor 45.154.73.71 as 65432;
    # source address <WAN_IPv4>;
    ipv4 {
        import filter accept_antifilter_download;
        export none;
    };
    multihop;
    hold time 240;
}
protocol bgp antifilter_network {
    local as 65103;
    neighbor 45.148.244.55 as 65444;
    # source address <WAN_IPv4>;
    ipv4 {
        import filter accept_antifilter_network_v4;
        export none;
    };
    ipv6 {
        import filter accept_antifilter_network_v6;
        export none;
    };
    multihop;
    hold time 240;
}
