#!/usr/local/bin/php
<?php
/**
 * Read/write os-dnstap-bgp files as key/value for the Xray DNStap tab.
 *
 *   xray-dnstap-conf.php get
 *   xray-dnstap-conf.php write
 */

const XRAY_DNSTAP_STAGED = '/tmp/xray_dnstap_write.json';
const XRAY_DNSTAP_MAX = 524288;
const XRAY_DNSTAP_FILES = [
    'conf'    => '/usr/local/etc/dnstap-bgp/dnstap-bgp.conf',
    'domains' => '/usr/local/etc/dnstap-bgp/domains.txt',
    'rc'      => '/usr/local/etc/rc.conf.d/dnstap_bgp',
];

function xray_dnstap_running(): bool
{
    exec('/usr/sbin/service dnstap_bgp onestatus 2>&1', $out, $rc);
    $text = strtolower(implode("\n", $out));
    if (strpos($text, 'not running') !== false) {
        return false;
    }
    return $rc === 0;
}

function xray_dnstap_read_file(string $path): string
{
    if (!is_readable($path)) {
        return '';
    }
    $raw = (string)file_get_contents($path);
    if (strlen($raw) > XRAY_DNSTAP_MAX) {
        return substr($raw, 0, XRAY_DNSTAP_MAX);
    }
    return $raw;
}

function xray_dnstap_write_file(string $path, string $body): bool
{
    $dir = dirname($path);
    if (!is_dir($dir)) {
        @mkdir($dir, 0755, true);
    }
    if (file_put_contents($path, $body) === false) {
        return false;
    }
    @chmod($path, 0644);
    return true;
}

function xray_dnstap_parse_toml_scalar(string $v)
{
    $v = trim($v);
    $v = rtrim($v, ',');
    if ($v === 'true') {
        return 'true';
    }
    if ($v === 'false') {
        return 'false';
    }
    if ($v !== '' && ($v[0] === '"' || $v[0] === "'")) {
        $q = $v[0];
        if (preg_match('/^' . preg_quote($q, '/') . '(.*)' . preg_quote($q, '/') . '/', $v, $m)) {
            return $m[1];
        }
    }
    if (preg_match('/^-?\d+$/', $v)) {
        return $v;
    }
    return $v;
}

function xray_dnstap_parse_toml(string $text): array
{
    $out     = [];
    $section = '';
    $arrKey  = null;
    $arr     = [];
    foreach (preg_split("/\r\n|\n|\r/", $text) as $line) {
        $trim = trim($line);
        if ($trim === '' || $trim[0] === '#') {
            continue;
        }
        if ($arrKey !== null) {
            if (strpos($trim, ']') === 0) {
                $out[] = ['key' => $arrKey, 'value' => implode(', ', $arr)];
                $arrKey = null;
                $arr    = [];
                continue;
            }
            if (preg_match('/^"([^"]*)"/', $trim, $m) || preg_match("/^'([^']*)'/", $trim, $m)) {
                $arr[] = $m[1];
            } elseif (preg_match('/^([^,#\]]+)/', $trim, $m)) {
                $item = trim($m[1], " \t\",");
                if ($item !== '') {
                    $arr[] = $item;
                }
            }
            continue;
        }
        if (preg_match('/^\[([^\]]+)\]/', $trim, $m)) {
            $section = trim($m[1]);
            continue;
        }
        if (preg_match('/^([A-Za-z0-9_]+)\s*=\s*(.*)$/', $trim, $m)) {
            $k = $section !== '' ? $section . '.' . $m[1] : $m[1];
            $v = trim($m[2]);
            if ($v === '[' || preg_match('/^\[\s*$/', $v)) {
                $arrKey = $k;
                $arr    = [];
                continue;
            }
            if (preg_match('/^\[(.*)\]$/', $v, $am)) {
                $items = [];
                if (preg_match_all('/"([^"]*)"/', $am[1], $qm)) {
                    $items = $qm[1];
                }
                $out[] = ['key' => $k, 'value' => implode(', ', $items)];
                continue;
            }
            $out[] = ['key' => $k, 'value' => (string)xray_dnstap_parse_toml_scalar($v)];
        }
    }
    if ($arrKey !== null) {
        $out[] = ['key' => $arrKey, 'value' => implode(', ', $arr)];
    }
    return $out;
}

function xray_dnstap_is_array_key(string $key): bool
{
    return substr($key, -6) === '.peers' || $key === 'peers';
}

function xray_dnstap_toml_scalar(string $key, string $v): string
{
    $v = trim($v);
    if ($v === 'true' || $v === 'false') {
        return $v;
    }
    if ($key === 'bgp.as' || $key === 'as' || preg_match('/^-?[1-9]\d*$/', $v) || $v === '0') {
        if (preg_match('/^-?\d+$/', $v) && ($v === '0' || $v[0] !== '0')) {
            return $v;
        }
    }
    return '"' . str_replace(['\\', '"'], ['\\\\', '\\"'], $v) . '"';
}

function xray_dnstap_render_toml(array $rows): string
{
    $root = [];
    $secs = [];
    foreach ($rows as $row) {
        $k = trim((string)($row['key'] ?? ''));
        $v = (string)($row['value'] ?? '');
        if ($k === '') {
            continue;
        }
        $dot = strpos($k, '.');
        if ($dot === false) {
            $root[] = [$k, $v];
        } else {
            $sec = substr($k, 0, $dot);
            $name = substr($k, $dot + 1);
            if (!isset($secs[$sec])) {
                $secs[$sec] = [];
            }
            $secs[$sec][] = [$name, $v, $k];
        }
    }
    $lines = [
        '# generated by os-xray DNStap tab',
        '',
    ];
    foreach ($root as [$k, $v]) {
        $lines[] = xray_dnstap_render_toml_assign($k, $v, $k);
    }
    foreach ($secs as $sec => $pairs) {
        $lines[] = '';
        $lines[] = '[' . $sec . ']';
        foreach ($pairs as [$name, $v, $full]) {
            $lines[] = xray_dnstap_render_toml_assign($name, $v, $full);
        }
    }
    return implode("\n", $lines) . "\n";
}

function xray_dnstap_render_toml_assign(string $name, string $v, string $fullKey): string
{
    if (xray_dnstap_is_array_key($fullKey)) {
        $items = [];
        foreach (preg_split('/\s*,\s*/', $v) as $item) {
            $item = trim($item);
            if ($item === '') {
                continue;
            }
            $items[] = '  "' . str_replace(['\\', '"'], ['\\\\', '\\"'], $item) . '",';
        }
        return $name . " = [\n" . implode("\n", $items) . "\n]";
    }
    return $name . ' = ' . xray_dnstap_toml_scalar($fullKey, $v);
}

function xray_dnstap_parse_rc(string $text): array
{
    $out = [];
    foreach (preg_split("/\r\n|\n|\r/", $text) as $line) {
        $trim = trim($line);
        if ($trim === '' || $trim[0] === '#') {
            continue;
        }
        if (preg_match('/^([A-Za-z0-9_]+)\s*=\s*"(.*)"\s*$/', $trim, $m)) {
            $out[] = ['key' => $m[1], 'value' => $m[2]];
            continue;
        }
        if (preg_match('/^([A-Za-z0-9_]+)\s*=\s*(\S+)\s*$/', $trim, $m)) {
            $out[] = ['key' => $m[1], 'value' => $m[2]];
        }
    }
    return $out;
}

function xray_dnstap_render_rc(array $rows): string
{
    $lines = [
        '# /usr/local/etc/rc.conf.d/dnstap_bgp',
        '# generated by os-xray DNStap tab',
        '',
    ];
    foreach ($rows as $row) {
        $k = trim((string)($row['key'] ?? ''));
        $v = (string)($row['value'] ?? '');
        if ($k === '' || !preg_match('/^[A-Za-z0-9_]+$/', $k)) {
            continue;
        }
        $lines[] = $k . '="' . str_replace(['\\', '"'], ['\\\\', '\\"'], $v) . '"';
    }
    return implode("\n", $lines) . "\n";
}

function xray_dnstap_parse_domains(string $text): array
{
    $out = [];
    foreach (preg_split("/\r\n|\n|\r/", $text) as $line) {
        $trim = trim($line);
        if ($trim === '' || $trim[0] === '#') {
            continue;
        }
        $out[] = ['key' => 'domain', 'value' => $trim];
    }
    return $out;
}

function xray_dnstap_render_domains(array $rows): string
{
    $lines = [
        '# One lowercase FQDN per line. IDN/punycode is not supported.',
        '',
    ];
    foreach ($rows as $row) {
        $v = strtolower(trim((string)($row['value'] ?? '')));
        if ($v === '' || $v[0] === '#') {
            continue;
        }
        $lines[] = $v;
    }
    return implode("\n", $lines) . "\n";
}

function xray_dnstap_rows_from_post($raw): array
{
    if (is_array($raw)) {
        $rows = [];
        foreach ($raw as $item) {
            if (is_array($item) && isset($item['key'])) {
                $rows[] = ['key' => (string)$item['key'], 'value' => (string)($item['value'] ?? '')];
            }
        }
        return $rows;
    }
    if (is_string($raw) && $raw !== '') {
        $j = json_decode($raw, true);
        if (is_array($j)) {
            return xray_dnstap_rows_from_post($j);
        }
    }
    return [];
}

$op = strtolower(trim((string)($argv[1] ?? 'get')));

if ($op === 'write') {
    if (!is_readable(XRAY_DNSTAP_STAGED)) {
        echo "OK\n";
        exit(0);
    }
    $j = json_decode((string)file_get_contents(XRAY_DNSTAP_STAGED), true);
    @unlink(XRAY_DNSTAP_STAGED);
    if (!is_array($j)) {
        echo "ERROR: invalid staged JSON\n";
        exit(1);
    }
    $map = [
        'conf'    => xray_dnstap_render_toml(xray_dnstap_rows_from_post($j['conf'] ?? [])),
        'domains' => xray_dnstap_render_domains(xray_dnstap_rows_from_post($j['domains'] ?? [])),
        'rc'      => xray_dnstap_render_rc(xray_dnstap_rows_from_post($j['rc'] ?? [])),
    ];
    foreach ($map as $key => $body) {
        if (strlen($body) > XRAY_DNSTAP_MAX) {
            echo "ERROR: {$key} too large\n";
            exit(1);
        }
        if (!xray_dnstap_write_file(XRAY_DNSTAP_FILES[$key], $body)) {
            echo "ERROR: cannot write " . XRAY_DNSTAP_FILES[$key] . "\n";
            exit(1);
        }
    }
    if (xray_dnstap_running()) {
        exec('/usr/sbin/service dnstap_bgp restart 2>&1');
        echo "OK dnstap_bgp restarted\n";
    } else {
        echo "OK files written, dnstap_bgp not running\n";
    }
    exit(0);
}

echo json_encode([
    'result'  => 'ok',
    'running' => xray_dnstap_running(),
    'paths'   => XRAY_DNSTAP_FILES,
    'conf'    => xray_dnstap_parse_toml(xray_dnstap_read_file(XRAY_DNSTAP_FILES['conf'])),
    'domains' => xray_dnstap_parse_domains(xray_dnstap_read_file(XRAY_DNSTAP_FILES['domains'])),
    'rc'      => xray_dnstap_parse_rc(xray_dnstap_read_file(XRAY_DNSTAP_FILES['rc'])),
], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . "\n";
