#!/usr/local/bin/php
<?php
/**
 * Выбор активного tun2socks для BIRD (ACTIVE_TUN4_IF / ACTIVE_TUN6_IF).
 *
 * Среди включённых инстансов с живыми xray-core и tun2socks:
 *   1. для IPv4 и IPv6 отдельно берётся больший Weight (weight_ipv4 / weight_ipv6);
 *   2. через SOCKS5 инстанса проверяется коннект (curl, как Test Connect);
 *   3. при равном весе побеждает меньшее «Время ответа» curl (time_total).
 *
 * Пишет:
 *   /usr/local/etc/bird/active_tun_v4.inc
 *   /usr/local/etc/bird/active_tun_v6.inc
 *
 * Вызывается перед service bird start/restart (onestart/onerestart).
 */

require_once('config.inc');

if (!defined('XRAY_BIRD_INC_DIR')) {
    define('XRAY_BIRD_INC_DIR', '/usr/local/etc/bird');
}
if (!defined('XRAY_AUTOROUTE_STATE')) {
    define('XRAY_AUTOROUTE_STATE', '/var/run/xray_autoroute_state.json');
}

function xray_bird_active_tun_pid_alive(string $pidfile): bool
{
    if (!is_readable($pidfile)) {
        return false;
    }
    $pid = (int)trim((string)file_get_contents($pidfile));
    if ($pid <= 0) {
        return false;
    }
    exec('/bin/kill -0 ' . $pid . ' 2>/dev/null', $out, $rc);
    return $rc === 0;
}

function xray_bird_active_tun_valid_if(string $tun): bool
{
    return preg_match('/^[a-z][a-z0-9]{0,13}[0-9]$/', $tun) === 1;
}

function xray_bird_active_tun_weight($raw): int
{
    $n = (int)(string)$raw;
    if ($n < 1) {
        return 1;
    }
    if ($n > 1000) {
        return 1000;
    }
    return $n;
}

/**
 * curl через SOCKS5. $ipFlag: '-4' или '-6'. Успех — HTTP 200–399.
 * @return array{ok:bool,http:int,time:float,raw:string}
 */
function xray_bird_active_tun_curl(string $listen, int $port, string $ipFlag): array
{
    $connectAddr = ($listen === '0.0.0.0') ? '127.0.0.1' : $listen;
    if ($port < 1 || $port > 65535) {
        $port = 10808;
    }
    $ipFlag = ($ipFlag === '-6') ? '-6' : '-4';
    $proxy = $connectAddr . ':' . $port;
    $out   = [];
    exec(
        '/usr/local/bin/curl ' . $ipFlag
        . ' --socks5 ' . escapeshellarg($proxy)
        . ' -s -L -o /dev/null'
        . ' -w ' . escapeshellarg("Код ответа: %{http_code}\nВремя ответа: %{time_total} сек\n")
        . ' ' . escapeshellarg('https://google.com')
        . ' --max-time 10',
        $out,
        $rc
    );
    $raw  = trim(implode("\n", $out));
    $http = 0;
    $time = 0.0;
    if (preg_match('/Код ответа:\s*(\d+)/u', $raw, $m)) {
        $http = (int)$m[1];
    }
    if (preg_match('/Время ответа:\s*([0-9.]+)/u', $raw, $m)) {
        $time = (float)$m[1];
    }
    $ok = ($rc === 0 && $http >= 200 && $http < 400);
    return ['ok' => $ok, 'http' => $http, 'time' => $time, 'raw' => $raw];
}

function xray_bird_active_tun_write(string $file, string $define, string $ifname): void
{
    $dir = dirname($file);
    if (!is_dir($dir)) {
        @mkdir($dir, 0755, true);
    }
    $body = "# generated by os-xray — active tun2socks (weight + curl)\n"
        . 'define ' . $define . ' = "' . $ifname . '";' . "\n";
    file_put_contents($file, $body);
    @chmod($file, 0644);
}

function xray_bird_active_tun_auto_route_on($general): bool
{
    return (string)($general->bgp_auto_route ?? '0') === '1';
}

function xray_bird_active_tun_poll_count($general): int
{
    if (!xray_bird_active_tun_auto_route_on($general)) {
        return 1;
    }
    $n = (int)(string)($general->bgp_auto_route_polls ?? 3);
    if ($n < 1) {
        return 1;
    }
    if ($n > 20) {
        return 20;
    }
    return $n;
}

/**
 * Несколько curl; среди успешных берётся минимальный time_total.
 * @return array{ok:bool,http:int,time:float,raw:string}
 */
function xray_bird_active_tun_curl_polls(string $listen, int $port, int $polls, string $ipFlag): array
{
    $best = ['ok' => false, 'http' => 0, 'time' => 0.0, 'raw' => ''];
    for ($i = 1; $i <= $polls; $i++) {
        $p = xray_bird_active_tun_curl($listen, $port, $ipFlag);
        echo "  {$ipFlag} poll {$i}/{$polls}: " . ($p['raw'] !== '' ? str_replace("\n", '; ', $p['raw']) : 'Код ответа: 0') . "\n";
        if ($p['ok'] && (!$best['ok'] || $p['time'] < $best['time'])) {
            $best = $p;
        }
    }
    return $best;
}

function xray_bird_active_tun_weight_used($general, string $family): bool
{
    if ($family === 'ipv6') {
        return (string)($general->bgp_weight_used_ipv6 ?? '0') === '1';
    }
    return (string)($general->bgp_weight_used_ipv4 ?? '0') === '1';
}

function xray_bird_active_tun_current(string $file, string $define): string
{
    if (!is_readable($file)) {
        return '';
    }
    $text = (string)file_get_contents($file);
    if (preg_match('/define\s+' . preg_quote($define, '/') . '\s*=\s*"([^"]+)"/', $text, $m)) {
        return $m[1];
    }
    return '';
}

function xray_bird_active_tun_pick(array $rows, string $weightKey, bool $useWeight): ?array
{
    if ($rows === []) {
        return null;
    }
    usort($rows, function ($a, $b) use ($weightKey, $useWeight) {
        if ($useWeight) {
            $wa = $a[$weightKey];
            $wb = $b[$weightKey];
            if ($wa !== $wb) {
                return $wb <=> $wa;
            }
        }
        if ($a['time'] !== $b['time']) {
            return $a['time'] <=> $b['time'];
        }
        return strcmp((string)$a['uuid'], (string)$b['uuid']);
    });
    return $rows[0];
}

function xray_bird_active_tun_candidates($ins): array
{
    $out = [];
    if (!$ins) {
        return $out;
    }
    foreach ($ins->instance as $inst) {
        $uuid = (string)$inst['uuid'];
        if ($uuid === '' || (string)($inst->enabled ?? '1') !== '1') {
            continue;
        }
        if (file_exists('/var/run/xray_stopped_' . $uuid . '.flag')) {
            continue;
        }
        if (!xray_bird_active_tun_pid_alive('/var/run/xray_core_' . $uuid . '.pid')) {
            continue;
        }
        if (!xray_bird_active_tun_pid_alive('/var/run/tun2socks_' . $uuid . '.pid')) {
            continue;
        }
        $use4 = (string)($inst->use_ipv4 ?? '1') === '1';
        $use6 = (string)($inst->use_ipv6 ?? '0') === '1';
        if (!$use4 && !$use6) {
            continue;
        }
        $tun = trim((string)($inst->tun_interface ?? ''));
        if ($tun === '') {
            $tun = 'proxytun2socks0';
        }
        if (!xray_bird_active_tun_valid_if($tun)) {
            continue;
        }
        $listen = (string)($inst->socks5_listen ?? '127.0.0.1') ?: '127.0.0.1';
        $port   = (int)(string)($inst->socks5_port ?? 10808);
        $out[] = [
            'uuid'      => $uuid,
            'name'      => (string)($inst->name ?? $uuid),
            'tun'       => $tun,
            'use4'      => $use4,
            'use6'      => $use6,
            'listen'    => $listen,
            'port'      => $port,
            'weight_v4' => xray_bird_active_tun_weight($inst->weight_ipv4 ?? 1),
            'weight_v6' => xray_bird_active_tun_weight($inst->weight_ipv6 ?? 1),
        ];
    }
    return $out;
}

/**
 * @return array{ok:bool, changed:bool}
 */
function xray_bird_active_tun_commit(?array $best4, ?array $best6, string $prev4, string $prev6): array
{
    $changed = false;
    if ($best4 !== null) {
        xray_bird_active_tun_write(
            XRAY_BIRD_INC_DIR . '/active_tun_v4.inc',
            'ACTIVE_TUN4_IF',
            $best4['tun']
        );
        $t = $best4['time'];
        echo "active tun v4: {$best4['tun']} ({$best4['name']}) weight={$best4['weight_v4']} time={$t}\n";
        if ($best4['tun'] !== $prev4) {
            $changed = true;
            echo "active tun v4 changed: {$prev4} -> {$best4['tun']}\n";
        }
    } else {
        echo "active tun v4: no working instance — file unchanged\n";
    }
    if ($best6 !== null) {
        xray_bird_active_tun_write(
            XRAY_BIRD_INC_DIR . '/active_tun_v6.inc',
            'ACTIVE_TUN6_IF',
            $best6['tun']
        );
        $t = $best6['time'];
        echo "active tun v6: {$best6['tun']} ({$best6['name']}) weight={$best6['weight_v6']} time={$t}\n";
        if ($best6['tun'] !== $prev6) {
            $changed = true;
            echo "active tun v6 changed: {$prev6} -> {$best6['tun']}\n";
        }
    } else {
        echo "active tun v6: no working instance — file unchanged\n";
    }
    $ok = ($best4 !== null || $best6 !== null);
    return ['ok' => $ok, 'changed' => $ok && $changed];
}

function xray_bird_avg_times(array $nums): ?float
{
    if ($nums === []) {
        return null;
    }
    return array_sum($nums) / count($nums);
}

function xray_bird_autoroute_empty(int $target = 3): array
{
    return [
        'polls_done'   => 0,
        'polls_target' => $target,
        'last_poll_at' => 0,
        'samples'      => [],
    ];
}

function xray_bird_autoroute_load(): array
{
    if (!is_readable(XRAY_AUTOROUTE_STATE)) {
        return xray_bird_autoroute_empty();
    }
    $j = json_decode((string)file_get_contents(XRAY_AUTOROUTE_STATE), true);
    if (!is_array($j)) {
        return xray_bird_autoroute_empty();
    }
    return array_merge(xray_bird_autoroute_empty(), $j);
}

function xray_bird_autoroute_save(array $state): void
{
    file_put_contents(
        XRAY_AUTOROUTE_STATE,
        json_encode($state, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES)
    );
    @chmod(XRAY_AUTOROUTE_STATE, 0644);
}

function xray_bird_autoroute_fmt(?float $v): string
{
    return $v === null ? 'n/a' : sprintf('%.3f', $v);
}

/**
 * Выбор по средним из накопленных попыток; затем пустой новый цикл.
 */
function xray_bird_autoroute_finalize(array $state, $general, string $reason): void
{
    echo "auto route: finalize ({$reason})\n";
    $v4ok = [];
    $v6ok = [];
    foreach ($state['samples'] as $uuid => $s) {
        $avg4 = xray_bird_avg_times($s['v4'] ?? []);
        $avg6 = xray_bird_avg_times($s['v6'] ?? []);
        $n4   = count($s['v4'] ?? []);
        $n6   = count($s['v6'] ?? []);
        echo "  [{$s['name']}] {$s['tun']} IPv4 samples=" . json_encode($s['v4'] ?? [])
            . " avg=" . xray_bird_autoroute_fmt($avg4) . " (n={$n4})"
            . " IPv6 samples=" . json_encode($s['v6'] ?? [])
            . " avg=" . xray_bird_autoroute_fmt($avg6) . " (n={$n6})\n";
        $base = [
            'uuid'      => (string)$uuid,
            'name'      => (string)($s['name'] ?? $uuid),
            'tun'       => (string)($s['tun'] ?? ''),
            'weight_v4' => (int)($s['weight_v4'] ?? 1),
            'weight_v6' => (int)($s['weight_v6'] ?? 1),
        ];
        if ($avg4 !== null && xray_bird_active_tun_valid_if($base['tun'])) {
            $v4ok[] = $base + ['time' => $avg4];
        }
        if ($avg6 !== null && xray_bird_active_tun_valid_if($base['tun'])) {
            $v6ok[] = $base + ['time' => $avg6];
        }
    }
    $best4 = xray_bird_active_tun_pick(
        $v4ok,
        'weight_v4',
        xray_bird_active_tun_weight_used($general, 'ipv4')
    );
    $best6 = xray_bird_active_tun_pick(
        $v6ok,
        'weight_v6',
        xray_bird_active_tun_weight_used($general, 'ipv6')
    );
    $prev4 = xray_bird_active_tun_current(XRAY_BIRD_INC_DIR . '/active_tun_v4.inc', 'ACTIVE_TUN4_IF');
    $prev6 = xray_bird_active_tun_current(XRAY_BIRD_INC_DIR . '/active_tun_v6.inc', 'ACTIVE_TUN6_IF');
    $res = xray_bird_active_tun_commit($best4, $best6, $prev4, $prev6);
    if (!empty($res['changed'])) {
        exec('/usr/sbin/service bird onerestart 2>&1');
        echo "bird: active tun changed — service bird onerestart\n";
    }
}

function xray_bird_autoroute_tick(): void
{
    $cfg     = OPNsense\Core\Config::getInstance()->object();
    $general = $cfg->OPNsense->xray->general ?? null;
    $ins     = $cfg->OPNsense->xray->instances ?? null;
    if ((string)($general->enabled ?? '0') !== '1' || (string)($general->bgp_enabled ?? '0') !== '1') {
        echo "auto route: plugin or BGP disabled\n";
        return;
    }
    if (!xray_bird_active_tun_auto_route_on($general)) {
        echo "auto route: disabled\n";
        return;
    }

    $now      = time();
    $interval = (int)(string)($general->bgp_auto_route_interval ?? 10);
    if ($interval < 1) {
        $interval = 10;
    }
    $target = (int)(string)($general->bgp_auto_route_polls ?? 3);
    if ($target < 1) {
        $target = 1;
    }
    if ($target > 20) {
        $target = 20;
    }

    $state = xray_bird_autoroute_load();
    if ((int)($state['polls_target'] ?? 0) !== $target && (int)($state['polls_done'] ?? 0) > 0) {
        echo "auto route: polls target changed, drop in-progress cycle\n";
        $state = xray_bird_autoroute_empty($target);
    }
    $state['polls_target'] = $target;

    $wait = $interval * 60;
    $last = (int)($state['last_poll_at'] ?? 0);
    if ($last > 0 && ($now - $last) < $wait) {
        echo 'auto route: next poll in ' . ($wait - ($now - $last)) . "s\n";
        return;
    }

    $cands = xray_bird_active_tun_candidates($ins);
    $round = (int)$state['polls_done'] + 1;
    echo "auto route: poll {$round}/{$target} (interval {$interval} min)\n";

    $ok4 = [];
    $ok6 = [];
    $byTun = [];
    foreach ($cands as $c) {
        $uuid = $c['uuid'];
        $byTun[$c['tun']] = $c;
        if (!isset($state['samples'][$uuid]) || !is_array($state['samples'][$uuid])) {
            $state['samples'][$uuid] = ['v4' => [], 'v6' => []];
        }
        $state['samples'][$uuid]['name']      = $c['name'];
        $state['samples'][$uuid]['tun']       = $c['tun'];
        $state['samples'][$uuid]['weight_v4'] = $c['weight_v4'];
        $state['samples'][$uuid]['weight_v6'] = $c['weight_v6'];
        $state['samples'][$uuid]['v4']        = $state['samples'][$uuid]['v4'] ?? [];
        $state['samples'][$uuid]['v6']        = $state['samples'][$uuid]['v6'] ?? [];

        echo "  [{$c['name']}] {$c['tun']} socks {$c['listen']}:{$c['port']}\n";
        if ($c['use4']) {
            $p = xray_bird_active_tun_curl($c['listen'], $c['port'], '-4');
            echo '    -4: ' . ($p['raw'] !== '' ? str_replace("\n", '; ', $p['raw']) : 'Код ответа: 0') . "\n";
            if ($p['ok']) {
                $state['samples'][$uuid]['v4'][] = $p['time'];
                $ok4[$uuid] = true;
            }
        }
        if ($c['use6']) {
            $p = xray_bird_active_tun_curl($c['listen'], $c['port'], '-6');
            echo '    -6: ' . ($p['raw'] !== '' ? str_replace("\n", '; ', $p['raw']) : 'Код ответа: 0') . "\n";
            if ($p['ok']) {
                $state['samples'][$uuid]['v6'][] = $p['time'];
                $ok6[$uuid] = true;
            }
        }
        $a4 = xray_bird_avg_times($state['samples'][$uuid]['v4']);
        $a6 = xray_bird_avg_times($state['samples'][$uuid]['v6']);
        echo '    running avg IPv4=' . xray_bird_autoroute_fmt($a4)
            . ' IPv6=' . xray_bird_autoroute_fmt($a6) . "\n";
    }

    $abort = false;
    $prev4 = xray_bird_active_tun_current(XRAY_BIRD_INC_DIR . '/active_tun_v4.inc', 'ACTIVE_TUN4_IF');
    $prev6 = xray_bird_active_tun_current(XRAY_BIRD_INC_DIR . '/active_tun_v6.inc', 'ACTIVE_TUN6_IF');
    if ($prev4 !== '') {
        $active = $byTun[$prev4] ?? null;
        if ($active === null || empty($active['use4']) || empty($ok4[$active['uuid']])) {
            echo "auto route: no connect through active IPv4 tun {$prev4} — abort cycle\n";
            $abort = true;
        }
    }
    if ($prev6 !== '') {
        $active = $byTun[$prev6] ?? null;
        if ($active === null || empty($active['use6']) || empty($ok6[$active['uuid']])) {
            echo "auto route: no connect through active IPv6 tun {$prev6} — abort cycle\n";
            $abort = true;
        }
    }

    $state['polls_done']   = $round;
    $state['last_poll_at'] = $now;
    xray_bird_autoroute_save($state);

    if ($abort || $round >= $target) {
        $reason = $abort ? 'active tun lost after poll ' . $round : "completed {$target} polls";
        xray_bird_autoroute_finalize($state, $general, $reason);
        $fresh = xray_bird_autoroute_empty($target);
        $fresh['last_poll_at'] = $now;
        xray_bird_autoroute_save($fresh);
        echo "auto route: new cycle starts after {$interval} min\n";
        return;
    }
    echo 'auto route: stored poll ' . $round . "/{$target} in " . XRAY_AUTOROUTE_STATE . "\n";
}

/**
 * Старт/рестарт BIRD: все попытки подряд в одном запуске, минимум time_total.
 *
 * @return array{ok:bool, changed:bool}
 */
function xray_bird_select_and_write_active_tun(): array
{
    $cfg     = OPNsense\Core\Config::getInstance()->object();
    $general = $cfg->OPNsense->xray->general ?? null;
    $ins     = $cfg->OPNsense->xray->instances ?? null;
    $v4ok    = [];
    $v6ok    = [];

    if ((string)($general->enabled ?? '0') !== '1' || !$ins) {
        echo "active tun: plugin disabled or no instances — files unchanged\n";
        return ['ok' => false, 'changed' => false];
    }

    $polls      = xray_bird_active_tun_poll_count($general);
    $useWeight4 = xray_bird_active_tun_weight_used($general, 'ipv4');
    $useWeight6 = xray_bird_active_tun_weight_used($general, 'ipv6');
    $prev4        = xray_bird_active_tun_current(XRAY_BIRD_INC_DIR . '/active_tun_v4.inc', 'ACTIVE_TUN4_IF');
    $prev6        = xray_bird_active_tun_current(XRAY_BIRD_INC_DIR . '/active_tun_v6.inc', 'ACTIVE_TUN6_IF');

    foreach ($ins->instance as $inst) {
        $uuid = (string)$inst['uuid'];
        if ($uuid === '' || (string)($inst->enabled ?? '1') !== '1') {
            continue;
        }
        if (file_exists('/var/run/xray_stopped_' . $uuid . '.flag')) {
            continue;
        }
        if (!xray_bird_active_tun_pid_alive('/var/run/xray_core_' . $uuid . '.pid')) {
            continue;
        }
        if (!xray_bird_active_tun_pid_alive('/var/run/tun2socks_' . $uuid . '.pid')) {
            continue;
        }

        $use4 = (string)($inst->use_ipv4 ?? '1') === '1';
        $use6 = (string)($inst->use_ipv6 ?? '0') === '1';
        if (!$use4 && !$use6) {
            continue;
        }

        $tun = trim((string)($inst->tun_interface ?? ''));
        if ($tun === '') {
            $tun = 'proxytun2socks0';
        }
        if (!xray_bird_active_tun_valid_if($tun)) {
            continue;
        }

        $name   = (string)($inst->name ?? $uuid);
        $listen = (string)($inst->socks5_listen ?? '127.0.0.1') ?: '127.0.0.1';
        $port   = (int)(string)($inst->socks5_port ?? 10808);
        $w4     = xray_bird_active_tun_weight($inst->weight_ipv4 ?? 1);
        $w6     = xray_bird_active_tun_weight($inst->weight_ipv6 ?? 1);

        echo "active tun [{$name}] {$tun} socks {$listen}:{$port} weight4={$w4} weight6={$w6} polls={$polls}\n";

        $base = [
            'uuid'      => $uuid,
            'name'      => $name,
            'tun'       => $tun,
            'weight_v4' => $w4,
            'weight_v6' => $w6,
        ];
        if ($use4) {
            $probe4 = xray_bird_active_tun_curl_polls($listen, $port, $polls, '-4');
            if ($probe4['ok']) {
                echo "  best -4: Код ответа: {$probe4['http']}; Время ответа: {$probe4['time']} сек\n";
                $v4ok[] = $base + ['time' => $probe4['time']];
            }
        }
        if ($use6) {
            $probe6 = xray_bird_active_tun_curl_polls($listen, $port, $polls, '-6');
            if ($probe6['ok']) {
                echo "  best -6: Код ответа: {$probe6['http']}; Время ответа: {$probe6['time']} сек\n";
                $v6ok[] = $base + ['time' => $probe6['time']];
            }
        }
    }

    $best4 = xray_bird_active_tun_pick($v4ok, 'weight_v4', $useWeight4);
    $best6 = xray_bird_active_tun_pick($v6ok, 'weight_v6', $useWeight6);
    return xray_bird_active_tun_commit($best4, $best6, $prev4, $prev6);
}

if (count(debug_backtrace()) === 0) {
    $mode = $argv[1] ?? '';
    if ($mode === 'autoroute') {
        xray_bird_autoroute_tick();
    } else {
        $sel = xray_bird_select_and_write_active_tun();
        if (!empty($sel['changed'])) {
            exec('/usr/sbin/service bird onerestart 2>&1');
            echo "bird: active tun changed — service bird onerestart\n";
        }
    }
}
